### ISSUE TITLE
Default LDAP Passwd

### ISSUE THREAD

**Issue by GeorgeGuoAT** [rgl/ldap-vagrant#1]
I download this repo and installed a LDAP server using vagrant,but i donot know the passwd of LDAP server.Can anyone told me?
Any reply would be appreciated.THX

**Comment by rgl** [comment]
Have a look at beginning of the [provision.sh](https://github.com/rgl/ldap-vagrant/blob/master/provision.sh) file (at the `config_admin_password` variable).
